apiVersion: v1
kind: Service
metadata:
  name: sts-demo-rwx
  labels:
    app: sts-demo-rwx
spec:
  clusterIP: None
  selector:
    app: sts-demo-rwx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-demo-rwx
spec:
  serviceName: "sts-demo"
  replicas: 1
  selector:
    matchLabels:
      app: sts-demo-rwx
  template:
    metadata:
      labels:
        app: sts-demo-rwx
    spec:
      containers:
      - name: busybox
        image: registry.k8s.io/busybox
        command: [ "sh", "-c"]
        args:
        - while true; do
            echo -en '\n';
            echo "${NODE_NAME}" "`date +"%Y-%m-%d %H:%M:%S"`"   >> /data/log.txt;
            sleep 1;
          done;
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 10Gi
